### ISSUE TITLE
Getting `Can't find our webpack executable at` error

### ISSUE THREAD

**Issue by tmartin8080** [febeling/webpack-rails-buildpack#1]
There is an error when deploying to Heroku: `Can't find our webpack executable at...`, and it asks if `npm install` was run.

**Comment by febeling** [comment]
@tmartin314 – what was the problem? I'd like to eliminate gotchas by improving the README, that's why I'm asking. And would this explanation 88d0d4ca4329b have helped?

**Comment by molefrog** [comment]
I had a similar problem (which I think is also related to #2). It turned out I simply didn't have nodejs buildpack installed. It didn't take much time to figure out, but was also confusing.
