### ISSUE TITLE
Issue in first installation

### ISSUE THREAD

**Issue by AlexGochu** [febeling/webpack-rails-buildpack#17]
Hi, I'm trying install using your instructions webpack-rails-buildpack
and receiving the error the last pat of it I want to share with you
...
remote: -----> bundle exec rake webpack:compile
remote: ** Invoke webpack:compile (first_time)
remote: ** Invoke environment (first_time)
remote: ** Execute environment
remote: ** Execute webpack:compile
remote: rake aborted!
remote: Can't find our webpack config file at /tmp/build_bf4a14785e9ae6614cc312a0e773388c/config/webpack.config.js
remote: /tmp/build_bf4a14785e9ae6614cc312a0e773388c/vendor/bundle/ruby/2.2.0/gems/webpack-rails-0.9.11/lib/tasks/webpack.rake:14:in `block (2 levels) in <top (required)>'
...

What was done wrong and how I can fix it?

**Comment by febeling** [comment]
Make sure that you have configured webpack-rails correctly for your app.

Then run `bundle exec rake webpack:compile`. Only if that completes successfully it will work with the buildpack.

**Comment by febeling** [comment]
Closing as inactive. Please reopen if the problem comes up again.
