### ISSUE TITLE
Could not find bundler?

### ISSUE THREAD

**Issue by iwarshak** [febeling/webpack-rails-buildpack#2]
I added this buildpack:

```
=== app-staging Buildpack URLs
1. heroku/nodejs
2. heroku/ruby
3. https://github.com/febeling/webpack-rails-buildpack.git
```

When I deploy, I get an error related to using `bundle exec`

```
remote: -----> Fetching set buildpack https://github.com/febeling/webpack-rails-buildpack.git... done
remote: -----> webpack-rails app detected
remote: -----> bundle exec rake webpack:compile
remote: /tmp/build_e79d1dc4352be15c4a65c94ee432b514/vendor/ruby-2.2.3/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'bundler' (>= 0) among 9 total gem(s) (Gem::LoadError)
remote: Checked in 'GEM_PATH=vendor/bundle/ruby/1.9.1:/tmp/build_e79d1dc4352be15c4a65c94ee432b514/vendor/ruby-2.2.3/lib/ruby/gems/2.2.0', execute `gem env` for more information
remote:     from /tmp/build_e79d1dc4352be15c4a65c94ee432b514/vendor/ruby-2.2.3/lib/ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
remote:     from /tmp/build_e79d1dc4352be15c4a65c94ee432b514/vendor/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
remote:     from /tmp/build_e79d1dc4352be15c4a65c94ee432b514/vendor/bundle/ruby/2.2.0/bin/bundle:22:in `<main>'
remote: 
remote:  !     Push rejected, failed to compile webpack-rails app
remote: 
```

Any ideas?

**Comment by febeling** [comment]
Sorry for the late response. No, no idea, unfortunately. 

Could you put the Gemfile in a Gist and add here?

**Comment by febeling** [comment]
@iwarshak – did you solve the problem?

**Comment by iwarshak** [comment]
@febeling - sorry I have not had time to revisit this yet.

**Comment by conorcussell** [comment]
I've got the same error, will reply if i find a solution today!

**Comment by conorcussell** [comment]
@febeling I've opened a PR to make the Dashboard vs CLI instructions more explicit https://github.com/febeling/webpack-rails-buildpack/pull/4

@iwarshak could you check what buildpacks are installed with

```
 heroku buildpacks
```

I think that, like me, you only had this buildpack installed and not ruby/nodejs

You should add the node and ruby buildpacks

```
 heroku buildpacks:add heroku/ruby
 heroku buildpacks:add --index 2 heroku/nodejs
```

and then add this buildpack in the last index

```
heroku buildpacks:add --index 3 https://github.com/febeling/webpack-rails-buildpack.git
```

**Comment by febeling** [comment]
Thanks for the PR, @conorcussell! ✨ Re-opening, as we still need confirmation that this also solves @iwarshak's problem.

**Comment by conorcussell** [comment]
@febeling I actually just re-read the original post from @iwarshak

I'm afraid it looks like we were having different issues, since his buildpacks are... 

> I added this buildpack:
> 
> === app-staging Buildpack URLs
> 1. heroku/nodejs
> 2. heroku/ruby
> 3. https://github.com/febeling/webpack-rails-buildpack.git

The only difference being mine are a different order

```
  1. heroku/ruby
  2. heroku/nodejs
  3. https://github.com/febeling/webpack-rails-buildpack.git
```

**Comment by febeling** [comment]
Yes, I also had the vague idea it was something different. Thanks for pinpointing it here.

**Comment by conorcussell** [comment]
Apologies, I should have read the post properly!

**Comment by febeling** [comment]
No new info in some time, so I'm assuming the problem solved and close; please reopen if the issue persists for anyone.

**Comment by acarpe** [comment]
I'm having this same issue trying to deploy my application.
Here is the Gemfile:
https://gist.github.com/acarpe/c8609c66e9126fa4ed997bd5a324c912

**Comment by conorcussell** [comment]
@acarpe Are you trying to deploy to Heroku?

If so, can you run the command `heroku buildpacks --app=YOUR_APP_NAME` and post the output?

**Comment by acarpe** [comment]
=== mamaclean-staging Buildpack URLs
1. heroku/nodejs
2. heroku/ruby
3. https://github.com/febeling/webpack-rails-buildpack.git

**Comment by acarpe** [comment]
It seems to me that the ruby buildpack is not exporting the bundle executable like the nodejs do [1] but I've not read the ruby buildpack source very well.

[1] https://github.com/heroku/heroku-buildpack-nodejs/blob/51ea78e68eccd980f72b9fc62c5e46187d869843/lib/environment.sh#L45-L46
