### ISSUE TITLE
Bundler conflicts with ruby-2.6.1/bin/bundle

### ISSUE THREAD

**Issue by ktaras** [febeling/webpack-rails-buildpack#22]
I'm using ruby 2.6.1 and bundler 2.0.1 for my ruby app.
When I was trying to deploy app I got the following error:

```
remote: -----> webpack-rails app detected
remote: -----> gem install bundler
remote: ERROR:  Error installing bundler:
remote: 	"bundle" from bundler conflicts with /tmp/build_5f23e64fd8050f5654d8fe6ab7e0bd8d/vendor/ruby-2.6.1/bin/bundle
remote:  !     Push rejected, failed to compile webpack-rails app.
remote:
remote:  !     Push failed
```

Is there any workaround to this issue?

**Comment by febeling** [comment]
Possibly related to rubygems/rubygems#2058.

Some people seem to run the bundler install with `--force` option, if I got that right. 

I don't have the bandwidth right now to look properly into it, though, unfortunately.

@ktaras you find a solution yet?

**Comment by ktaras** [comment]
@febeling thanks.
I had to downgrade ruby to version 2.5.3 and bundler to 1.17.3. I'm planning to migrate to `webpacker` anyway, so it's a temporary fix.
