### ISSUE TITLE
nodejs webpack doesn't detect package.json file

### ISSUE THREAD

**Issue by fastjames** [febeling/webpack-rails-buildpack#6]
I'm not sure if this is a problem with the heroku nodejs buildpack or with this project, but I figured I would start here. I'm attempting to use the webpack-rails gem (https://github.com/mipearson/webpack-rails) with an app hosted on github. The author links to this project as a way to include the running webpack server that's required for the gem in heroku. I have added the required buildpacks to my app and I have both a Gemfile and a package.json file in the root of my project directory, but heroku returns an error when I attempt to push to it (see [gist](https://gist.github.com/fastjames/39ea3f5fea15681e678543782448f3e6) for proof). I read the source for the official nodejs buildpack, and the detect script seems to be very simple. I tried forking the repo and adding some debugging, but heroku appears to swallow all output from the detect script. Is there another way to figure out what's going on?

**Comment by febeling** [comment]
Can you confirm that you have a `package.json` in `master` branch, not just in `working-feature` branch?

**Comment by febeling** [comment]
Closing – please reopen if the problem persists.
