### ISSUE TITLE
Error in webpack compile step does not fail the deploy

### ISSUE THREAD

**Issue by alismith-dev** [febeling/webpack-rails-buildpack#9]
If there is an error in the webpack compile (for example if webpack is misconfigured), then the `webpack:compile` rake task aborts but does not fail the deploy.

I believe this can be done by setting the `errexit` flag in bash. This is done by the official nodejs buildpack: https://github.com/heroku/heroku-buildpack-nodejs/blob/047dbbf1dcbd83d719b5394dabc5fcd7dc316ff6/bin/compile#L6

**Comment by febeling** [comment]
Thanks for the report! It's fixed.

**Comment by alismith-dev** [comment]
Great! Thanks for the super quick response 🎉
